# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
# New Architecture 비활성화 (콜백 브리지 호환성 목적)
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_FRAMEWORKS'] = 'static'
# Hermes iOS에서 동적 Framework 사용 비활성화(정적 링크 강제)
ENV['HERMES_ENABLE_FRAMEWORKS'] = '0'
# React Native 공식 플래그: Hermes를 프리빌트가 아닌 "소스 빌드"로 강제
# https://github.com/facebook/react-native/blob/main/packages/react-native/sdks/hermes-engine/hermes-utils.rb
ENV['RCT_BUILD_HERMES_FROM_SOURCE'] = 'true'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SmartDoorManager' do
  config = use_native_modules!
  
  # AppAuth for react-native-app-auth (호환성을 위해 1.7.0 사용)
  pod 'AppAuth', '~> 1.7.0', :modular_headers => true
  # MSAL for iOS native authentication (Microsoft official)
  pod 'MSAL'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Ensure dSYM is generated for Release (fix App Store Connect dSYM check)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.name == 'Release'
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
          config.build_settings['COPY_PHASE_STRIP'] = 'NO'
        end
      end
    end
  end
end
